# Generated by Django 4.0.8 on 2023-02-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontdisplay',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
